# Generated by Django 5.2.3 on 2026-02-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='seen_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
