# Generated by Django 5.2.3 on 2026-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaverequest_seen_by_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
