# Generated by Django 5.2.3 on 2026-02-25 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_broadcastread'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='read_by',
            field=models.ManyToManyField(blank=True, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='sender',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BroadcastRead',
        ),
    ]
