# Generated by Django 5.2.3 on 2026-03-01 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_broadcast_sender_warden'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='target_role',
            field=models.CharField(choices=[('student', 'Student'), ('warden', 'Warden'), ('mess', 'Mess Manager')], default='student', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
