# Generated by Django 5.2.3 on 2026-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_broadcast_target_role_alter_broadcast_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_seen_by_warden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
