# Generated by Django 5.2.3 on 2026-03-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_leaveapplication_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
    ]
