# Generated by Django 5.2.3 on 2026-03-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_student_address_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_edit_profile',
            field=models.BooleanField(default=False),
        ),
    ]
