# Generated by Django 5.2.3 on 2026-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_student_can_edit_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, choices=[('electrical', 'Electrical Work'), ('plumbing', 'Plumbing'), ('carpentry', 'Carpentry'), ('cleaning', 'Cleaning & Hygiene'), ('network', 'Network / Wi-Fi'), ('food', 'Food & Mess'), ('safety', 'Safety & Security'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion')], default='complaint', max_length=20),
        ),
    ]
