# Generated by Django 5.2.3 on 2026-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_complaint_category_complaint_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('announcement', 'Announcement'), ('urgent', 'Urgent'), ('meeting', 'Meeting')], default='general', max_length=20),
        ),
    ]
