# Generated by Django 5.2.3 on 2026-02-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdailyrecord',
            name='attendance_marked',
        ),
        migrations.RemoveField(
            model_name='studentdailyrecord',
            name='presence_verified',
        ),
        migrations.AddField(
            model_name='studentdailyrecord',
            name='present',
            field=models.BooleanField(null=True),
        ),
    ]
