# Generated by Django 5.2.3 on 2026-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_studentdailyrecord_attendance_marked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdailyrecord',
            name='present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
