# Generated by Django 5.2.3 on 2026-02-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_studentdailyrecord_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdailyrecord',
            name='breakfast',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdailyrecord',
            name='dinner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdailyrecord',
            name='lunch',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
