# Generated by Django 5.2.3 on 2026-03-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_studentdailyrecord_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdailyrecord',
            name='marked_by',
            field=models.CharField(blank=True, choices=[('student', 'Marked by Student'), ('warden', 'Marked by Warden'), ('auto', 'Auto (Approved Leave)')], max_length=20, null=True),
        ),
    ]
