# Generated by Django 5.2.3 on 2026-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_parent_email'),
        ('food', '0005_studentdailyrecord_marked_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdailyrecord',
            unique_together={('student', 'date')},
        ),
    ]
